### ISSUE TITLE
Ternary Operator

### ISSUE THREAD

**Issue by bmwalters** [meepdarknessmeep/lau#2]
7:33 PM - Zerf: meep, real ternary operator?
7:33 PM - Zerf: true and false or true
7:33 PM - $: true
7:33 PM - Zerf: see that should be false
7:34 PM - Zerf: i mean
7:34 PM - Zerf: it shouldn't
7:34 PM - Zerf: but with a ternary operator it should
7:39 PM - Zerf: function Ternary(condition, a, b) if condition then return a else return b end end
7:39 PM - Zerf: Ternary(true, false, true)
7:39 PM - $: false
7:39 PM - Zerf: see
7:39 PM - Zerf: as opposed to
7:39 PM - Zerf: true and false or true
7:39 PM - $: true
7:40 PM - Meepen [aim-flex]: oh ok
7:40 PM - Zerf: yes
7:40 PM - Zerf: but it would have the condition ? a : b syntax
7:40 PM - Zerf: as opposed to a function call

**Comment by meepen** [comment]
added

```
check a then b else c
```
