### ISSUE TITLE
Concise function syntax.

### ISSUE THREAD

**Issue by MDFL64** [meepdarknessmeep/lau#4]
I like languages like dart and coffeescript and all that other fuckboy not-javascript shit because I don't actually have to type the word fucntion which I always end up mispelling anyway.

Obviously if we use -> it would be too fukkin mainstream and i dont know exactly how you want to design the sintax and where u wanna go with that but plz credit me as lead idea guy also base it off of laujit instead its faster

**Comment by mcd1992** [comment]
10/10 hire this man
