### ISSUE TITLE
Switch + and -

### ISSUE THREAD

**Issue by MDFL64** [meepdarknessmeep/lau#5]
I think sasha(?) said if we ever make an esoteric anglage we shoudl switch + and - because - is easier to hit and you dont need temp-capslock for it and adding is also more important than take-away. Just make sure to keep using - for urinary minus because im betting you all of my chucky cheese tokens that's going to break someone s ballsack

i know lleaf is not a esoterlic langlidge but it actaully seems like a really good idea

sorry if it wasnt actualty u sash i dont mean to discredit anyone from assistant idea guy position

**Comment by mcd1992** [comment]
:+1:
